name: Release Drafter

on:
  push:
    branches: [main]

permissions:
  contents: read

jobs:
  release-drafter:
    uses: ./.github/workflows/pheno-release-drafter.yml
    permissions:
      contents: write
      pull-requests: write
