name: Tag Automation

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  push:
    tags:
      - 'v*'

jobs:
  tag:
    uses: ./.github/workflows/pheno-tag-automation.yml
    permissions:
      contents: write
